openapi: 3.0.1
info:
  title: API de Productos
  version: 1.0.0
  description: API para gestionar productos, incluyendo la creación, actualización, eliminación y obtención de productos.

paths:
  /api/productos:
    get:
      summary: Obtiene una lista de productos.
      description: Devuelve una lista de todos los productos disponibles.
      tags:
        - Productos
      responses:
        '200':
          description: Lista de productos
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      description: El identificador único del producto
                    nombre:
                      type: string
                      description: El nombre del producto
                    precio:
                      type: number
                      format: float
                      description: El precio del producto
                    descripcion:
                      type: string
                      description: La descripción del producto
        '500':
          description: Error interno del servidor

    post:
      summary: Crea un nuevo producto.
      description: Añade un nuevo producto y devuelve el producto creado.
      tags:
        - Productos
      requestBody:
        description: Información del nuevo producto.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre:
                  type: string
                  description: El nombre del producto
                precio:
                  type: number
                  format: float
                  description: El precio del producto
                descripcion:
                  type: string
                  description: La descripción del producto
      responses:
        '201':
          description: Producto creado exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    description: Mensaje de confirmación
                  producto:
                    type: object
                    properties:
                      id:
                        type: string
                        description: El identificador único del producto
                      nombre:
                        type: string
                        description: El nombre del producto
                      precio:
                        type: number
                        format: float
                        description: El precio del producto
                      descripcion:
                        type: string
                        description: La descripción del producto
        '500':
          description: Error interno del servidor

  /api/productos/{pid}:
    get:
      summary: Obtiene un producto por su ID.
      description: Devuelve los detalles de un producto específico utilizando su identificador único.
      tags:
        - Productos
      parameters:
        - in: path
          name: pid
          required: true
          description: El identificador único del producto
          schema:
            type: string
      responses:
        '200':
          description: Detalles del producto
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: El identificador único del producto
                  nombre:
                    type: string
                    description: El nombre del producto
                  precio:
                    type: number
                    format: float
                    description: El precio del producto
                  descripcion:
                    type: string
                    description: La descripción del producto
        '404':
          description: Producto no encontrado
        '500':
          description: Error interno del servidor

    put:
      summary: Actualiza un producto existente.
      description: Actualiza la información de un producto específico.
      tags:
        - Productos
      parameters:
        - in: path
          name: pid
          required: true
          description: El identificador único del producto
          schema:
            type: string
      requestBody:
        description: Información actualizada del producto.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre:
                  type: string
                  description: El nombre del producto
                precio:
                  type: number
                  format: float
                  description: El precio del producto
                descripcion:
                  type: string
                  description: La descripción del producto
      responses:
        '200':
          description: Producto actualizado exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    description: Mensaje de confirmación
                  producto:
                    type: object
                    properties:
                      id:
                        type: string
                        description: El identificador único del producto
                      nombre:
                        type: string
                        description: El nombre del producto
                      precio:
                        type: number
                        format: float
                        description: El precio del producto
                      descripcion:
                        type: string
                        description: La descripción del producto
        '404':
          description: Producto no encontrado
        '500':
          description: Error interno del servidor

    delete:
      summary: Elimina un producto por su ID.
      description: Elimina un producto específico utilizando su identificador único.
      tags:
        - Productos
      parameters:
        - in: path
          name: pid
          required: true
          description: El identificador único del producto
          schema:
            type: string
      responses:
        '200':
          description: Producto eliminado exitosamente
        '404':
          description: Producto no encontrado
        '500':
          description: Error interno del servidor
